# NGINX
nginx_http_port: 80
nginx_https_port: 443

nginx_packages:
  - nginx
  - php

# Linux
linux_dir_info:
  - { dir_path: '/work', dir_owner: 'root', dir_group: 'root', dir_mode: '0755' }
  - { dir_path: '/work/tmp', dir_owner: 'root', dir_group: 'root', dir_mode: '0755' }
  - { dir_path: '/work/InstallMedia', dir_owner: 'root', dir_group: 'root', dir_mode: '0755' }
  - { dir_path: '/log', dir_owner: 'root', dir_group: 'root', dir_mode: '0755' }
  - { dir_path: '/log/app', dir_owner: 'root', dir_group: 'root', dir_mode: '0755' }
  - { dir_path: '/log/web', dir_owner: 'root', dir_group: 'root', dir_mode: '0755' }

linux_part_info:
  - { part_devname: '/dev/sdb', part_number: '1', part_label: 'msdos' }
  - { part_devname: '/dev/sdc', part_number: '1', part_label: 'msdos' }

linux_fs_info:
  - { fs_dev: '/dev/sdb1', fs_type: 'xfs' }
  - { fs_dev: '/dev/sdc1', fs_type: 'xfs' }

linux_systemd_info:
  - { service_name: 'chronyd', service_enabled: 'yes' }
  - { service_name: 'crond', service_enabled: 'yes' }
  - { service_name: 'firewalld', service_enabled: 'no' }
  - { service_name: 'kdump', service_enabled: 'yes' }
  - { service_name: 'sshd', service_enabled: 'yes' }
  - { service_name: 'sysstat', service_enabled: 'yes' }

