- hosts: all
  vars:
    target_nic: enp0s8
    nic_method: manual

  tasks:
    - name: Network interfaces configuration
      shell: |
        set -e
        aaa=$(nmcli c s {{ target_nic }} | grep "^ipv4.method.*manual.*$")
        if [[ $? -ne 0 ]]; then
          nmcli c m "{{ target_nic }}" ipv4.method manual
          echo "_changed_" >&2
        fi
        echo $aaa
      register: result
      changed_when: '"_changed_" in result.stderr_lines'
      become: yes

    - name: debug
      debug:
        msg: "{{ result }}"


