- hosts: all
  vars:
    target_nic: enp0s8
    nic_method: manual

  tasks:
    - name: get interface informations
      shell: nmcli c s {{ item.dev_name }} | grep "^ipv4.method.*{{ item.ipv4_method }}.*$"
      register: result
      check_mode: no
      changed_when: false
      become: yes
      with_items:
        - "{{ linux_interfaces }}"

    - name: debug
      debug:
        msg: "{{ result }}"

    - name: nic
      shell: "nmcli c m {{ item.dev_name }} ipv4.method {{ item.ipv4_method }}"
      when: result.rc == 1
      with_items:
        - "{{ linux_interfaces }}"

