- hosts: all
  vars:
    target_nic: enp0s8
    nic_method: manual

  tasks:
    - name: get interface informations
      shell: nmcli c s {{ target_nic }} | grep "^ipv4.method.*$"
      register: result
      become: yes
      check_mode: no
      changed_when: false

    - name: debug
      debug:
        msg: "{{ result }}"

    - name: nic
      shell: "nmcli c m {{ target_nic }} ipv4.method {{ nic_method }}"
      when: nic_method not in result.stdout

