- name: Modules installation
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ linux_modules }}"
  become: yes

- name: Modules installation persistent
  copy:
    src: etc/modprobe.d/custom.conf
    dest: /etc/modprobe.d/custom.conf
    owner: root
    group: root
    mode: 644
  become: yes
