- name: Kernel parameter configuration
  sysctl:
    name: "{{ item.kernel_parm }}"
    value: "{{ item.kernel_value }}"
    state: present
    sysctl_file: "/etc/sysctl.d/k8s.conf"
  with_items:
    - "{{ linux_sysctl_info }}"
  register: result
  become: yes
  notify: load sysctl
